version: '3.8'
services:
  ruby-app:
    build:
      args:
        - RAILS_ENV
      context: .
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: ruby-app
      ASERTO_AUTHORIZER_SERVICE_URL: topaz:8282
      ASERTO_DIRECTORY_SERVICE_URL: topaz:9292
      ASERTO_AUTHORIZER_CERT_PATH: "/certs/grpc-ca.crt"
      ASERTO_DIRECTORY_GRPC_CERT_PATH: "/certs/grpc-ca.crt"
    volumes:
      - "$PWD:/ruby-app"
      - ./topaz/certs:/certs
    ports:
      - 3001:3001
